---
- name: Installing and Launch Filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download filebeat .deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-darw>


  - name: Install filebeat .deb
    command: tar xzvf filebeat-7.6.1-darwin-x86_64.tar.gz


  - name: Drop in filebeat.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml


  - name: Enable and Configure System Module
    command: filebeat modules enable system


  - name: Setup filebeat
    command: filebeat setup


  - name: Start filebeat service
    command: service filebeat start


  - name: Enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes

